# Generated by Django 4.2.7 on 2023-11-08 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_id", models.CharField(blank=True, max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MAN", "MAN"),
                            ("WOMAN", "WOMAN"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=100,
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="")),
                ("dob", models.DateField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
