# Generated by Django 4.2.7 on 2023-12-18 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_branch_comment_emoji_organization_post_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="person_id",
            new_name="personID",
        ),
    ]
