# Generated by Django 4.2.7 on 2023-12-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_person_id_person_personid"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="isCompleted",
            field=models.BooleanField(default=False),
        ),
    ]
