# Generated by Django 4.1.1 on 2023-12-19 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trip_iscompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='orgID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
    ]
