# Generated by Django 4.1.1 on 2023-12-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_trip_orgid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
