# Generated by Django 4.1.1 on 2023-12-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_trip_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
