# Generated by Django 4.1.1 on 2023-12-19 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_trip_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='date',
        ),
    ]
