# Generated by Django 4.1.1 on 2023-12-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_trip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TimeField(null=True),
        ),
    ]
