# Generated by Django 4.1.1 on 2023-12-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_trip_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='orgID',
        ),
    ]
