# Generated by Django 4.1.1 on 2023-12-19 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_trip_orgid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='orgID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
    ]
