# Generated by Django 4.2.7 on 2023-12-20 01:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_trip_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="password",
        ),
    ]
