# Generated by Django 4.2.7 on 2023-12-20 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_remove_organization_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="branchID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.branch",
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="postID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.post",
            ),
        ),
    ]
