# Generated by Django 4.2.7 on 2023-12-20 03:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_advertisement_branchid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertisement",
            name="location",
        ),
    ]
