# Generated by Django 4.2.7 on 2023-12-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_customuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="participants",
            field=models.ManyToManyField(
                blank=True, default="", related_name="participants", to="core.person"
            ),
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
